In [2]:
import os
import glob
import pandas as pd
import numpy as np
import json

In [5]:
os.getcwd()

'/home/spai0722'

In [29]:
base_dir = "Bidcoin"  # Bidcoin 폴더 경로 (상대/절대 경로로 수정 가능)

# Bidcoin 폴더 안의 json 파일 목록 가져오기
json_paths = glob.glob(os.path.join(base_dir, "*.json"))

dfs = dict() # category별 RAGAS 점수
for path in json_paths:
    df = pd.read_json(path)
    category = df['category'].iloc[0]
    ragas = pd.DataFrame([i for i in df['evaluation']]).fillna(0).mean().to_dict()
    dfs[category] = ragas

In [7]:
a = pd.read_json(r"/home/spai0722/Bidcoin/eval_results_20260416_014028.json")

In [14]:
pd.DataFrame([i for i in a['evaluation']]).fillna(0).head().mean().to_dict()

{'faithfulness': 0.46875,
 'answer_relevancy': 0.0,
 'context_precision': 0.39583333331770804,
 'context_recall': 0.24999999999999978,
 'answer_correctness': 0.0397189327740355}

In [30]:
dfs

{'condition': {'faithfulness': 0.76,
  'answer_relevancy': 0.3198887186480572,
  'context_precision': 0.9999999999666661,
  'context_recall': 0.5,
  'answer_correctness': 0.33394360336957063},
 'recommend': {'faithfulness': 0.0,
  'answer_relevancy': 0.0,
  'context_precision': 0.0,
  'context_recall': 0.22222222222222202,
  'answer_correctness': 0.140596358308952},
 'follow_up': {'faithfulness': 0.6,
  'answer_relevancy': 0.14363474901423168,
  'context_precision': 0.9999999999666661,
  'context_recall': 0.8333333333333334,
  'answer_correctness': 0.11276650861175468},
 'summary': {'faithfulness': 0.5,
  'answer_relevancy': 0.6151864653341867,
  'context_precision': 0.9999999999624996,
  'context_recall': 1.0,
  'answer_correctness': 0.5146730701569833},
 'compare': {'faithfulness': 0.46875,
  'answer_relevancy': 0.0,
  'context_precision': 0.39583333331770804,
  'context_recall': 0.24999999999999978,
  'answer_correctness': 0.0397189327740355},
 'refusal': {'faithfulness': 0.16666666666666666,
  'answer_relevancy': 0.0,
  'context_precision': 0.0,
  'context_recall': 0.3333333333333333,
  'answer_correctness': 0.2925280509927974},
 'complex': {'faithfulness': 0.0,
  'answer_relevancy': 0.0,
  'context_precision': 0.9999999999666661,
  'context_recall': 0.75,
  'answer_correctness': 0.0},
 'fact': {'faithfulness': 0.8999999999999998,
  'answer_relevancy': 0.3447092922558836,
  'context_precision': 0.8571428571142852,
  'context_recall': 0.7619047619047619,
  'answer_correctness': 0.4817150147666552},
 'evidence': {'faithfulness': 0.611111111111111,
  'answer_relevancy': 0.5125117721680551,
  'context_precision': 0.9444444444083328,
  'context_recall': 1.0,
  'answer_correctness': 0.191713962650641}}

In [31]:
df_final = pd.DataFrame(dfs)
df_final

,condition,recommend,follow_up,summary,compare,refusal,complex,fact,evidence
faithfulness,0.760000,0.000000,0.600000,0.500000,0.468750,0.166667,0.00,0.900000,0.611111
answer_relevancy,0.319889,0.000000,0.143635,0.615186,0.000000,0.000000,0.00,0.344709,0.512512
context_precision,1.000000,0.000000,1.000000,1.000000,0.395833,0.000000,1.00,0.857143,0.944444
context_recall,0.500000,0.222222,0.833333,1.000000,0.250000,0.333333,0.75,0.761905,1.000000
answer_correctness,0.333944,0.140596,0.112767,0.514673,0.039719,0.292528,0.00,0.481715,0.191714

In [33]:
df_final.T.sort_values(by='faithfulness', ascending=False)

,faithfulness,answer_relevancy,context_precision,context_recall,answer_correctness
fact,0.900000,0.344709,0.857143,0.761905,0.481715
condition,0.760000,0.319889,1.000000,0.500000,0.333944
evidence,0.611111,0.512512,0.944444,1.000000,0.191714
follow_up,0.600000,0.143635,1.000000,0.833333,0.112767
summary,0.500000,0.615186,1.000000,1.000000,0.514673
compare,0.468750,0.000000,0.395833,0.250000,0.039719
refusal,0.166667,0.000000,0.000000,0.333333,0.292528
recommend,0.000000,0.000000,0.000000,0.222222,0.140596
complex,0.000000,0.000000,1.000000,0.750000,0.000000

In [43]:
df_final.to_csv("ragas_scores_by_category.csv", index=False)

In [41]:
df_a = pd.read_json(r"/home/spai0722/Bidcoin/eval_results_20260416_060524.json")
df_a.drop(columns=['id', 'query', 'example_answer', 'answer'], inplace=True)
df_b = df_a.groupby('category').apply(lambda x: pd.DataFrame([i for i in x['evaluation']]).fillna(0).mean()).T
df_b

category,compare,complex,condition,evidence,fact,follow_up,recommend,refusal,summary
hit_rate,0.500000,0.500000,1.000000,1.000000,1.000000,1.000000,0.00000,0.333333,1.000000
precision,0.500000,0.500000,1.000000,1.000000,1.000000,1.000000,0.00000,0.333333,1.000000
recall,0.625000,1.500000,3.000000,3.000000,3.000000,3.000000,0.00000,0.666667,3.000000
mrr,0.500000,0.500000,1.000000,1.000000,1.000000,1.000000,0.00000,0.333333,1.000000
ndcg,0.500000,0.500000,1.000000,1.000000,1.000000,1.000000,0.00000,0.333333,1.000000
f1,0.076590,0.185886,0.098246,0.208669,0.200546,0.115302,0.09176,0.204196,0.147271
faithfulness,0.227083,0.382353,0.469487,0.649393,0.529670,0.375817,0.00000,0.083333,0.469179

In [42]:
df_b.to_csv("retrieval_experiments_summary1.csv", index=False)